name: 'Fandogh action'
description: 'Fandogh CI/CD action'
author: Amirhossein Meydani
branding:
  color: blue
  icon: minimize-2

inputs:
  username:
    description: 'Fandogh account username'
    required: true
  password:
    description: 'Fandogh account password'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Fandogh action
      run: |
        pip install fandogh_cli --upgrade
      shell: bash
    - name: Fandogh login
      run: fandogh login --username=${{ inputs.username }} --password=${{ inputs.password }}
      shell: bash
  