name: 'Fandogh action'
description: 'Fandogh CI/CD action'
author: Amirhossein Meydani
branding:
  color: blue
  icon: minimize-2

inputs:
  username:
    description: 'Fandogh account username'
    required: true
  password:
    description: 'Fandogh account password'
    required: true
  
runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ github.action_path }}/src/fandogh-action.sh
      env:
        FANDOGH_USERNAME: ${{ inputs.username }}
        FANDOGH_PASSWORD: ${{ inputs.password }}
      shell: bash
